{% set name = "robotframework-requests" %}
{% set version = "0.8.1" %}
{% set sha256 = "b26f4ae617ff8c4b522fba422b7c8f83545a98aec3e2deb7f1aa53dcd68defe2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - requests
    - requests_ntlm
    - robotframework

test:
  imports:
    - RequestsLibrary

about:
  home: https://github.com/MarketSquare/robotframework-requests
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RequestsLibrary is a Robot Framework test library that uses the Requests HTTP client.

extra:
  recipe-maintainers:
    - daniel88ferreira
